FROM node:10-alpine

RUN npm config set unsafe-perm true
RUN npm install -g http-server

RUN mkdir /usr/front
WORKDIR /usr/front
COPY package.json package-lock.json ./

RUN npm install 

COPY . .

RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]